basePath: /
definitions:
  models.Schedule:
    properties:
      client_name:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      end_lat:
        type: number
      end_lon:
        type: number
      end_time:
        type: string
      id:
        type: integer
      location:
        type: string
      shift_time:
        type: string
      start_lat:
        type: number
      start_lon:
        type: number
      start_time:
        type: string
      status:
        enum:
        - scheduled
        - in_progress
        - completed
        - cancelled
        type: string
      tasks:
        items:
          $ref: '#/definitions/models.Task'
        type: array
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - client_name
    - location
    - shift_time
    - status
    type: object
  models.Task:
    properties:
      completed_at:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      reason:
        type: string
      schedule_id:
        type: integer
      status:
        enum:
        - completed
        - not_completed
        type: string
      updated_at:
        type: string
    required:
    - description
    - status
    type: object
  models.VisitLocationRequest:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    required:
    - latitude
    - longitude
    type: object
info:
  contact:
    name: Devs In Kenya
    url: http://devsinkenya.com
  description: API for Electronic Visit Verification and caregiver scheduling
  title: Caregiver Shift Tracker API
  version: "1.0"
paths:
  /schedules:
    get:
      description: Fetch all schedules for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: List of schedules
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all schedules
      tags:
      - Schedules
  /schedules/{id}:
    get:
      description: Fetch a specific schedule by ID
      parameters:
      - description: Schedule ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Schedule details
          schema:
            $ref: '#/definitions/models.Schedule'
        "400":
          description: Invalid ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get schedule details
      tags:
      - Schedules
  /schedules/end/{id}:
    post:
      consumes:
      - application/json
      description: End a visit for a specific schedule by ID
      parameters:
      - description: Schedule ID
        in: path
        name: id
        required: true
        type: integer
      - description: End location coordinates
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VisitLocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Visit ended
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: End visit
      tags:
      - Schedules
  /schedules/start/{id}:
    post:
      consumes:
      - application/json
      description: Start a visit for a specific schedule by ID
      parameters:
      - description: Schedule ID
        in: path
        name: id
        required: true
        type: integer
      - description: Start location coordinates
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VisitLocationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Visit started
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Start visit
      tags:
      - Schedules
  /schedules/today:
    get:
      description: Fetch today's schedules for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: List of today's schedules
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get today's schedules
      tags:
      - Schedules
  /tasks:
    post:
      consumes:
      - application/json
      description: Allows admin to create a task for a caregiver schedule
      parameters:
      - description: Task Info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new task
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      description: Deletes a task by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Delete a task
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: Updates task details by its ID
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated task data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Update a task
      tags:
      - Tasks
  /tasks/assign/{id}:
    post:
      consumes:
      - application/json
      description: Assigns one or more tasks to a specific schedule ID
      parameters:
      - description: Schedule ID
        in: path
        name: id
        required: true
        type: integer
      - description: List of Tasks
        in: body
        name: request
        required: true
        schema:
          properties:
            tasks:
              items:
                $ref: '#/definitions/models.Task'
              type: array
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Assign tasks to a schedule
      tags:
      - Tasks
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
